SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_INVOICE_PROTOCOL_ZNVLS') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_INVOICE_PROTOCOL_ZNVLS AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_INVOICE_PROTOCOL_ZNVLS
    @XMLPARAM NTEXT AS

DECLARE @HDOC INT
DECLARE @ID_GLOBAL UNIQUEIDENTIFIER
DECLARE @DOCSUP varchar (50)
DECLARE @DOCSAL varchar (50)

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT

SELECT
	@ID_GLOBAL = ID_GLOBAL
FROM OPENXML(@HDOC, '/XML') WITH
(
	ID_GLOBAL UNIQUEIDENTIFIER 'ID_GLOBAL'
)

EXEC SP_XML_REMOVEDOCUMENT @HDOC

SET @DOCSUP = (SELECT TOP 1 ' ' +ISNULL (INCOMING_NUMBER,'') +' от '+ ISNULL (CONVERT(nvarchar, INCOMING_DATE, 102) ,'') FROM INVOICE WHERE ID_INVOICE_GLOBAL = @ID_GLOBAL)
SET @DOCSAL = (SELECT TOP 1 ' ' +MNEMOCODE + ' от ' + CONVERT(NVARCHAR, DOCUMENT_DATE,102) FROM INVOICE WHERE ID_INVOICE_GLOBAL = @ID_GLOBAL)
declare @IS_ENVD bit
select @IS_ENVD = 1 - c.USE_VAT
from CONTRACTOR	c
join STORE		s	on s.ID_CONTRACTOR = c.ID_CONTRACTOR
join INVOICE	i	on i.ID_STORE = s.ID_STORE
where
	i.ID_INVOICE_GLOBAL = @ID_GLOBAL

SELECT
	FR_NAME	= CASE WHEN ISNULL(C_FR.FULL_NAME, '') = '' THEN C_FR.NAME +@DOCSUP ELSE C_FR.FULL_NAME + @DOCSUP END,
	TO_NAME	= CASE WHEN ISNULL(C_TO.FULL_NAME, '') = '' THEN C_TO.NAME +@DOCSAL ELSE C_TO.FULL_NAME + @DOCSAL END,
	DIR		= C_TO.DIRECTOR_FIO
FROM INVOICE I
join STORE		S		ON I.ID_STORE = S.ID_STORE
join CONTRACTOR	C_TO	ON C_TO.ID_CONTRACTOR = S.ID_CONTRACTOR
join CONTRACTOR	C_FR	ON C_FR.ID_CONTRACTOR = I.ID_CONTRACTOR_SUPPLIER
WHERE
	I.ID_INVOICE_GLOBAL = @ID_GLOBAL

SELECT
    BARCODE =  ISNULL(II.BAR_CODE,''),
	GOODS_NAME		= g.NAME,
	SERIES_NAME		= ISNULL(s.SERIES_NUMBER,''),
	PRODUCER_NAME	= p.NAME,
	REGISTER_PRICE	= l.REGISTER_PRICE,
	PRICE_PROD		= ii.PRODUCER_PRICE,
	ADPRICE_SUP		= ii.SUPPLIER_ADPRICE,
	ADPRICE_SUP_SUM	= ii.SUPPLIER_PRICE - ii.PRODUCER_PRICE,
	PRICE_SUP		= ii.SUPPLIER_PRICE,
	ADPRICE_SAL		= l.ADPRICE_SAL,
	ADPRICE_SAL_SUM	= case when @IS_ENVD = 1 then ii.RETAIL_PRICE_VAT - ii.SUPPLIER_PRICE_VAT else ii.RETAIL_PRICE - ii.SUPPLIER_PRICE end,
	PRICE_SAL		= case when @IS_ENVD = 1 then ii.RETAIL_PRICE_VAT else ii.RETAIL_PRICE end,
	PRICE_PROD_WNDS = ii.PRODUCER_PRICE*1.1,
	PRICE_SUP_WNDS = II.SUPPLIER_PRICE_VAT,
	MNN = ISNULL(SUB.NAME,'')

from INVOICE_ITEM	ii
join GOODS			g	on g.ID_GOODS = ii.ID_GOODS
join PRODUCER		p	on p.ID_PRODUCER = g.ID_PRODUCER
join LOT			l	on l.ID_DOCUMENT_ITEM = ii.ID_INVOICE_ITEM_GLOBAL
LEFT JOIN SERIES	s	on s.ID_SERIES = ii.ID_SERIES	
LEFT JOIN SUBSTANCE SUB ON SUB.ID_SUBSTANCE = G.ID_SUBSTANCE
where
	ii.ID_INVOICE_GLOBAL = @ID_GLOBAL AND
	g.IMPORTANT = 1
order by
	g.NAME

RETURN 0
GO

--exec REPEX_INVOICE_PROTOCOL_ZNVLS N'<XML><ID_GLOBAL>1663b23d-3d87-48ac-8ccd-266ee0df8c60</ID_GLOBAL></XML>'